[package]
name = "mamoru-core-go"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[profile.release]
# optimize for binary size
opt-level = "z"
strip = true
lto = true

[dependencies]
query-validator-c = {git = "https://github.com/Mamoru-Foundation/mamoru-core", rev = "716357e07d2e59e7fd133a155eeaa9e9e579c776"}
playbook-engine-c = {git = "https://github.com/Mamoru-Foundation/mamoru-core", rev = "716357e07d2e59e7fd133a155eeaa9e9e579c776"}

# query-validator-c = {path = "../mamoru-core/query-validator-c"}
# playbook-engine-c = {path = "../mamoru-core/playbook-engine-c"}
