[package]
name = "mamoru-core-go"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[profile.release]
# optimize for binary size
opt-level = "z"
strip = true
lto = true

[dependencies]
query-validator-c = {git = "https://github.com/Mamoru-Foundation/mamoru-core", rev = "a1bf0a4eb6a21224d8693a8045b0f11f0527212b"}
playbook-engine-c = {git = "https://github.com/Mamoru-Foundation/mamoru-core", rev = "a1bf0a4eb6a21224d8693a8045b0f11f0527212b"}

# query-validator-c = {path = "../mamoru-core/query-validator-c"}
# playbook-engine-c = {path = "../mamoru-core/playbook-engine-c"}
