[package]
name = "mamoru-core-go"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib"]

[profile.release]
# optimize for binary size
opt-level = "z"
strip = true
lto = true

[dependencies]
query-validator-c = {git = "https://github.com/Mamoru-Foundation/mamoru-core", rev = "acdf6c892724d6a58719c07cbc0b080b4aa5a5ea"}
playbook-engine-c = {git = "https://github.com/Mamoru-Foundation/mamoru-core", rev = "acdf6c892724d6a58719c07cbc0b080b4aa5a5ea"}

#query-validator-c = {path = "../mamoru-core/query-validator-c"}
#playbook-engine-c = {path = "../mamoru-core/playbook-engine-c"}
