/*! \file */
/*******************************************
 *                                         *
 *  File auto-generated by `::safer_ffi`.  *
 *                                         *
 *  Do not manually edit this file.        *
 *                                         *
 *******************************************/

#ifndef __RUST_QUERY_VALIDATOR_C__
#define __RUST_QUERY_VALIDATOR_C__

#ifdef __cplusplus
extern "C" {
#endif


#include <stddef.h>
#include <stdint.h>

/** \remark Has the same ABI as `uint8_t` **/
#ifdef DOXYGEN
typedef enum FfiChainType
#else
typedef uint8_t FfiChainType_t; enum
#endif
{
    /** . */
    FFI_CHAIN_TYPE_SUI = 0,
    /** . */
    FFI_CHAIN_TYPE_EVM = 1,
    /** . */
    FFI_CHAIN_TYPE_APTOS = 2,
    /** . */
    FFI_CHAIN_TYPE_COSMOS = 3,
}
#ifdef DOXYGEN
FfiChainType_t
#endif
;

typedef struct FfiDaemonParameters FfiDaemonParameters_t;

typedef struct FfiDaemonVersions FfiDaemonVersions_t;


#include <stdbool.h>

typedef struct FfiValidationResult {

    bool is_error;

    char * message;

} FfiValidationResult_t;

/** \brief
 *  Drops `parameters` argument.
 */
FfiValidationResult_t ffi_validate_sql (
    FfiChainType_t chain,
    char const * query,
    FfiDaemonParameters_t * parameters,
    FfiDaemonVersions_t * versions);

/** \brief
 *  Drops `parameters` argument.
 */
FfiValidationResult_t ffi_validate_sql_renders (
    char const * query,
    FfiDaemonParameters_t * parameters,
    FfiDaemonVersions_t * versions);

void ffi_drop_validation_result (
    FfiValidationResult_t result);

FfiDaemonParameters_t * ffi_new_daemon_parameters (void);

void ffi_append_daemon_parameter (
    FfiDaemonParameters_t * parameters,
    char const * key,
    char const * value);

FfiDaemonVersions_t * ffi_new_daemon_versions (void);

FfiValidationResult_t ffi_append_daemon_version (
    FfiDaemonVersions_t * versions,
    char const * key,
    char const * value);

void ffi_drop_daemon_versions (
    FfiDaemonVersions_t * versions);


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* __RUST_QUERY_VALIDATOR_C__ */
