// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 25 Mar 2024 18:56:35 WET.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include <libmamoru_query_validator_go.h>
#include <libmamoru_playbook_engine_go.h>
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

