// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Mon, 22 Apr 2024 19:42:01 WEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package generated_bindings

/*
#cgo CFLAGS: -I${SRCDIR}/../packaged/include
#cgo LDFLAGS: -lmamoru_core_go
#cgo darwin,arm64 LDFLAGS: -L${SRCDIR}/../packaged/lib/darwin-arm64
#cgo darwin,amd64 LDFLAGS: -L${SRCDIR}/../packaged/lib/darwin-amd64
#cgo linux,amd64 LDFLAGS: -Wl,--no-as-needed -ldl -lm -L${SRCDIR}/../packaged/lib/linux-amd64
#include <libmamoru_query_validator_go.h>
#include <libmamoru_playbook_engine_go.h>
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"fmt"
	"runtime"
	"sync"
	"unsafe"
)

// cgoAllocMap stores pointers to C allocated memory for future reference.
type cgoAllocMap struct {
	mux sync.RWMutex
	m   map[unsafe.Pointer]struct{}
}

var cgoAllocsUnknown = new(cgoAllocMap)

func (a *cgoAllocMap) Add(ptr unsafe.Pointer) {
	a.mux.Lock()
	if a.m == nil {
		a.m = make(map[unsafe.Pointer]struct{})
	}
	a.m[ptr] = struct{}{}
	a.mux.Unlock()
}

func (a *cgoAllocMap) IsEmpty() bool {
	a.mux.RLock()
	isEmpty := len(a.m) == 0
	a.mux.RUnlock()
	return isEmpty
}

func (a *cgoAllocMap) Borrow(b *cgoAllocMap) {
	if b == nil || b.IsEmpty() {
		return
	}
	b.mux.Lock()
	a.mux.Lock()
	for ptr := range b.m {
		if a.m == nil {
			a.m = make(map[unsafe.Pointer]struct{})
		}
		a.m[ptr] = struct{}{}
		delete(b.m, ptr)
	}
	a.mux.Unlock()
	b.mux.Unlock()
}

func (a *cgoAllocMap) Free() {
	a.mux.Lock()
	for ptr := range a.m {
		C.free(ptr)
		delete(a.m, ptr)
	}
	a.mux.Unlock()
}

// allocFfiJsonResultTMemory allocates memory for type C.FfiJsonResult_t in C.
// The caller is responsible for freeing the this memory via C.free.
func allocFfiJsonResultTMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfFfiJsonResultTValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfFfiJsonResultTValue = unsafe.Sizeof([1]C.FfiJsonResult_t{})

// Ref returns the underlying reference to C object or nil if struct is nil.
func (x *FfiJsonResultT) Ref() *C.FfiJsonResult_t {
	if x == nil {
		return nil
	}
	return x.reff1382d49
}

// Free invokes alloc map's free mechanism that cleanups any allocated memory using C free.
// Does nothing if struct is nil or has no allocation map.
func (x *FfiJsonResultT) Free() {
	if x != nil && x.allocsf1382d49 != nil {
		x.allocsf1382d49.(*cgoAllocMap).Free()
		x.reff1382d49 = nil
	}
}

// NewFfiJsonResultTRef creates a new wrapper struct with underlying reference set to the original C object.
// Returns nil if the provided pointer to C object is nil too.
func NewFfiJsonResultTRef(ref unsafe.Pointer) *FfiJsonResultT {
	if ref == nil {
		return nil
	}
	obj := new(FfiJsonResultT)
	obj.reff1382d49 = (*C.FfiJsonResult_t)(unsafe.Pointer(ref))
	return obj
}

// PassRef returns the underlying C object, otherwise it will allocate one and set its values
// from this wrapping struct, counting allocations into an allocation map.
func (x *FfiJsonResultT) PassRef() (*C.FfiJsonResult_t, *cgoAllocMap) {
	if x == nil {
		return nil, nil
	} else if x.reff1382d49 != nil {
		return x.reff1382d49, nil
	}
	memf1382d49 := allocFfiJsonResultTMemory(1)
	reff1382d49 := (*C.FfiJsonResult_t)(memf1382d49)
	allocsf1382d49 := new(cgoAllocMap)
	allocsf1382d49.Add(memf1382d49)

	var cis_error_allocs *cgoAllocMap
	reff1382d49.is_error, cis_error_allocs = (C._Bool)(x.IsError), cgoAllocsUnknown
	allocsf1382d49.Borrow(cis_error_allocs)

	var cerror_message_allocs *cgoAllocMap
	reff1382d49.error_message, cerror_message_allocs = *(**C.char)(unsafe.Pointer(&x.ErrorMessage)), cgoAllocsUnknown
	allocsf1382d49.Borrow(cerror_message_allocs)

	var cresult_json_allocs *cgoAllocMap
	reff1382d49.result_json, cresult_json_allocs = *(**C.char)(unsafe.Pointer(&x.ResultJson)), cgoAllocsUnknown
	allocsf1382d49.Borrow(cresult_json_allocs)

	x.reff1382d49 = reff1382d49
	x.allocsf1382d49 = allocsf1382d49
	return reff1382d49, allocsf1382d49

}

// PassValue does the same as PassRef except that it will try to dereference the returned pointer.
func (x FfiJsonResultT) PassValue() (C.FfiJsonResult_t, *cgoAllocMap) {
	if x.reff1382d49 != nil {
		return *x.reff1382d49, nil
	}
	ref, allocs := x.PassRef()
	return *ref, allocs
}

// Deref uses the underlying reference to C object and fills the wrapping struct with values.
// Do not forget to call this method whether you get a struct for C object and want to read its values.
func (x *FfiJsonResultT) Deref() {
	if x.reff1382d49 == nil {
		return
	}
	x.IsError = (bool)(x.reff1382d49.is_error)
	x.ErrorMessage = (*byte)(unsafe.Pointer(x.reff1382d49.error_message))
	x.ResultJson = (*byte)(unsafe.Pointer(x.reff1382d49.result_json))
}

// Ref returns a reference to C object as it is.
func (x *FfiDaemonParametersT) Ref() *C.FfiDaemonParameters_t {
	if x == nil {
		return nil
	}
	return (*C.FfiDaemonParameters_t)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *FfiDaemonParametersT) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewFfiDaemonParametersTRef converts the C object reference into a raw struct reference without wrapping.
func NewFfiDaemonParametersTRef(ref unsafe.Pointer) *FfiDaemonParametersT {
	return (*FfiDaemonParametersT)(ref)
}

// NewFfiDaemonParametersT allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func NewFfiDaemonParametersT() *FfiDaemonParametersT {
	return (*FfiDaemonParametersT)(allocFfiDaemonParametersTMemory(1))
}

// allocFfiDaemonParametersTMemory allocates memory for type C.FfiDaemonParameters_t in C.
// The caller is responsible for freeing the this memory via C.free.
func allocFfiDaemonParametersTMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfFfiDaemonParametersTValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfFfiDaemonParametersTValue = unsafe.Sizeof([1]C.FfiDaemonParameters_t{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *FfiDaemonParametersT) PassRef() *C.FfiDaemonParameters_t {
	if x == nil {
		x = (*FfiDaemonParametersT)(allocFfiDaemonParametersTMemory(1))
	}
	return (*C.FfiDaemonParameters_t)(unsafe.Pointer(x))
}

// Ref returns a reference to C object as it is.
func (x *FfiDaemonVersionsT) Ref() *C.FfiDaemonVersions_t {
	if x == nil {
		return nil
	}
	return (*C.FfiDaemonVersions_t)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *FfiDaemonVersionsT) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewFfiDaemonVersionsTRef converts the C object reference into a raw struct reference without wrapping.
func NewFfiDaemonVersionsTRef(ref unsafe.Pointer) *FfiDaemonVersionsT {
	return (*FfiDaemonVersionsT)(ref)
}

// NewFfiDaemonVersionsT allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func NewFfiDaemonVersionsT() *FfiDaemonVersionsT {
	return (*FfiDaemonVersionsT)(allocFfiDaemonVersionsTMemory(1))
}

// allocFfiDaemonVersionsTMemory allocates memory for type C.FfiDaemonVersions_t in C.
// The caller is responsible for freeing the this memory via C.free.
func allocFfiDaemonVersionsTMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfFfiDaemonVersionsTValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfFfiDaemonVersionsTValue = unsafe.Sizeof([1]C.FfiDaemonVersions_t{})

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *FfiDaemonVersionsT) PassRef() *C.FfiDaemonVersions_t {
	if x == nil {
		x = (*FfiDaemonVersionsT)(allocFfiDaemonVersionsTMemory(1))
	}
	return (*C.FfiDaemonVersions_t)(unsafe.Pointer(x))
}

// allocFfiValidationResultTMemory allocates memory for type C.FfiValidationResult_t in C.
// The caller is responsible for freeing the this memory via C.free.
func allocFfiValidationResultTMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfFfiValidationResultTValue))
	if mem == nil {
		panic(fmt.Sprintln("memory alloc error: ", err))
	}
	return mem
}

const sizeOfFfiValidationResultTValue = unsafe.Sizeof([1]C.FfiValidationResult_t{})

// Ref returns the underlying reference to C object or nil if struct is nil.
func (x *FfiValidationResultT) Ref() *C.FfiValidationResult_t {
	if x == nil {
		return nil
	}
	return x.ref5dc80852
}

// Free invokes alloc map's free mechanism that cleanups any allocated memory using C free.
// Does nothing if struct is nil or has no allocation map.
func (x *FfiValidationResultT) Free() {
	if x != nil && x.allocs5dc80852 != nil {
		x.allocs5dc80852.(*cgoAllocMap).Free()
		x.ref5dc80852 = nil
	}
}

// NewFfiValidationResultTRef creates a new wrapper struct with underlying reference set to the original C object.
// Returns nil if the provided pointer to C object is nil too.
func NewFfiValidationResultTRef(ref unsafe.Pointer) *FfiValidationResultT {
	if ref == nil {
		return nil
	}
	obj := new(FfiValidationResultT)
	obj.ref5dc80852 = (*C.FfiValidationResult_t)(unsafe.Pointer(ref))
	return obj
}

// PassRef returns the underlying C object, otherwise it will allocate one and set its values
// from this wrapping struct, counting allocations into an allocation map.
func (x *FfiValidationResultT) PassRef() (*C.FfiValidationResult_t, *cgoAllocMap) {
	if x == nil {
		return nil, nil
	} else if x.ref5dc80852 != nil {
		return x.ref5dc80852, nil
	}
	mem5dc80852 := allocFfiValidationResultTMemory(1)
	ref5dc80852 := (*C.FfiValidationResult_t)(mem5dc80852)
	allocs5dc80852 := new(cgoAllocMap)
	allocs5dc80852.Add(mem5dc80852)

	var cis_error_allocs *cgoAllocMap
	ref5dc80852.is_error, cis_error_allocs = (C._Bool)(x.IsError), cgoAllocsUnknown
	allocs5dc80852.Borrow(cis_error_allocs)

	var cmessage_allocs *cgoAllocMap
	ref5dc80852.message, cmessage_allocs = *(**C.char)(unsafe.Pointer(&x.Message)), cgoAllocsUnknown
	allocs5dc80852.Borrow(cmessage_allocs)

	x.ref5dc80852 = ref5dc80852
	x.allocs5dc80852 = allocs5dc80852
	return ref5dc80852, allocs5dc80852

}

// PassValue does the same as PassRef except that it will try to dereference the returned pointer.
func (x FfiValidationResultT) PassValue() (C.FfiValidationResult_t, *cgoAllocMap) {
	if x.ref5dc80852 != nil {
		return *x.ref5dc80852, nil
	}
	ref, allocs := x.PassRef()
	return *ref, allocs
}

// Deref uses the underlying reference to C object and fills the wrapping struct with values.
// Do not forget to call this method whether you get a struct for C object and want to read its values.
func (x *FfiValidationResultT) Deref() {
	if x.ref5dc80852 == nil {
		return
	}
	x.IsError = (bool)(x.ref5dc80852.is_error)
	x.Message = (*byte)(unsafe.Pointer(x.ref5dc80852.message))
}

// safeString ensures that the string is NULL-terminated, a NULL-terminated copy is created otherwise.
func safeString(str string) string {
	if len(str) > 0 && str[len(str)-1] != '\x00' {
		str = str + "\x00"
	} else if len(str) == 0 {
		str = "\x00"
	}
	return str
}

// unpackPCharString copies the data from Go string as *C.char.
func unpackPCharString(str string) (*C.char, *cgoAllocMap) {
	allocs := new(cgoAllocMap)
	defer runtime.SetFinalizer(allocs, func(a *cgoAllocMap) {
		go a.Free()
	})

	str = safeString(str)
	mem0 := unsafe.Pointer(C.CString(str))
	allocs.Add(mem0)
	return (*C.char)(mem0), allocs
}

type stringHeader struct {
	Data unsafe.Pointer
	Len  int
}
