// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Fri, 25 Aug 2023 17:50:37 CEST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package generated_bindings
