// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 26 Mar 2024 17:25:38 WET.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package generated_bindings
